"use client";

import { Info } from "@phosphor-icons/react";

import { useAssembly } from "../../../lib/workflow-context";

export default function PreferencesRoute() {
  const workflow = useAssembly();
  const { preferences } = workflow;
  return <section className="module-screen preferences-screen" aria-labelledby="preferences-page-title"><div className="module-heading"><div><h1 id="preferences-page-title">Appearance and accessibility</h1><p>These preferences apply only to this browser. They never contain account or security data.</p></div></div><div className="preferences-list"><fieldset><legend>Theme</legend>{(["system", "light", "dark"] as const).map((theme) => <label key={theme}><input checked={preferences.theme === theme} name="theme" onChange={() => workflow.updatePreferences({ theme })} type="radio" /> {theme === "system" ? "Use device setting" : `${theme.charAt(0).toUpperCase()}${theme.slice(1)} theme`}</label>)}</fieldset><fieldset><legend>Contrast</legend><label><input checked={preferences.contrast === "standard"} name="contrast" onChange={() => workflow.updatePreferences({ contrast: "standard" })} type="radio" /> Standard contrast</label><label><input checked={preferences.contrast === "high"} name="contrast" onChange={() => workflow.updatePreferences({ contrast: "high" })} type="radio" /> High contrast</label></fieldset><fieldset><legend>Motion</legend><label><input checked={preferences.motion === "system"} name="motion" onChange={() => workflow.updatePreferences({ motion: "system" })} type="radio" /> Follow device preference</label><label><input checked={preferences.motion === "reduced"} name="motion" onChange={() => workflow.updatePreferences({ motion: "reduced" })} type="radio" /> Reduce non-essential motion</label></fieldset><fieldset><legend>Community view</legend><label><input checked={preferences.inventoryView === "graph"} name="community-view" onChange={() => workflow.updatePreferences({ inventoryView: "graph" })} type="radio" /> Graph view</label><label><input checked={preferences.inventoryView === "list"} name="community-view" onChange={() => workflow.updatePreferences({ inventoryView: "list" })} type="radio" /> List view</label></fieldset><div className="preference-note"><Info aria-hidden="true" size={18} weight="duotone" /><p>Only theme, contrast, motion and inventory view are stored in the versioned ASSEMBLE UI preference cookie. Judge Proof Mode remains session-only.</p></div></div></section>;
}
